version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: forum-site-mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=forum-site-db
    volumes:
      - /Database/forum-site:/var/lib/mysql