service:
  port: ":8000"
  secretJWT: "SECRET"

database:
  dataSourceName: "postgres://admin:admin@localhost:5433/music-app-db?sslmode=disable"

spotifyConfig:
  clientID: "eb7268df25c64485aedb1fd32dcc4e45"
  clientSecret: "199aad8c5b884fab88dcdf35dde218c7"
