CREATE TABLE `posts` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NOT NULL,
  `post_title` varchar(255) NOT NULL,
  `post_content` LONGTEXT NOT NULL,
  `post_hastags` LONGTEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` LONGTEXT NOT NULL,
  `updated_by` LONGTEXT NOT NULL
)